### ISSUE TITLE
[Suggestion] Better Preview Image

### ISSUE THREAD

**Issue by ghost** [Arcafanetiz/Baro-conversation-pack#1]
Hello,

I made some art about your mod icon. It's only a suggestion.

This is 500 x 500 image:
![community-conversation-pack500x500](https://user-images.githubusercontent.com/57105419/112762453-0a2c3080-9000-11eb-9495-014ce394fb44.png)

Original (1000x1000):
![community-conversation-pack](https://user-images.githubusercontent.com/57105419/112762356-883c0780-8fff-11eb-844a-9ff00857898f.png)

Xcf file (Gimp 2.10 file), if you want to edit something in the image:
[community-conversation-pack.xcf.zip](https://github.com/Arcafanetiz/Baro-conversation-pack/files/6217784/community-conversation-pack.xcf.zip)

Generally my art is on MIT License so you can use it without any problem. 

Feel free to ask something if you want.

Also: In next days I will prepare my fork to make pull request to your stuff. Exactly Polish translations.

**Comment by Arcrentan** [comment]
Ahhhh, thank you, and you may need to update the fork's structure to be like main branch, but with your translation in a folder as an addition

**Comment by ghost** [comment]
Pull request is done, image was updated, so i can close this issue.
